Repository phase2/outline, pull requests merged in 2021-12, with the labels that each got.

#126 Add conditional slot template method to `outline-element`
  src/components/base/outline-element/outline-element.ts
Labels: Type: Enhancement, Ready for Review

#136 Vimeo Video component
  src/components/base/outline-video-vimeo/outline-video-vimeo.css
  src/components/base/outline-video-vimeo/outline-video-vimeo.stories.ts
  src/components/base/outline-video-vimeo/outline-video-vimeo.ts
Labels: Ready for Review

#193 fix: update Gitpod setup with Storybook port 6042
  .gitpod.yml
Labels: Ready for Review

#194 Organize Readme and Contributing instructions
  CONTRIBUTING.md
  README.md
Labels: Ready for Review

#195 Storybook Deprecation Cleanup
  src/.storybook/stories/documentation/tooling.stories.mdx
  src/.storybook/stories/documentation/welcome.stories.mdx
  src/.storybook/stories/guides/contributing.stories.mdx
  src/.storybook/stories/protons/spacing.stories.mdx
  src/.storybook/stories/protons/typefaces.stories.mdx
  src/components/base/outline-accordion/outline-accordion.stories.ts
  src/components/base/outline-button/outline-button.stories.ts
  src/components/base/outline-card/outline-card.stories.ts
  src/components/base/outline-container/outline-container.stories.ts
  src/components/base/outline-grid/outline-column/outline-column.stories.ts
  src/components/base/outline-heading/outline-heading.stories.ts
  src/components/base/outline-icon/outline-icon.stories.mdx
  src/components/base/outline-link/config.ts
  src/components/base/outline-list/outline-list.stories.ts
  src/components/base/outline-tabs/outline-tab-group/outline-tab-group.stories.ts
Labels: Why: Update dependencies, Ready for Review

#191 Updates for outline-container & outline-grid
  outline.theme.css
  src/.storybook/stories/documentation/tooling.stories.mdx
  src/.storybook/storybook-styles.css
  src/components/base/outline-container/outline-container.css
  src/components/base/outline-container/outline-container.stories.ts
  src/components/base/outline-container/outline-container.ts
  src/components/base/outline-grid/outline-grid.css
  src/components/base/outline-grid/outline-grid.stories.ts
  src/components/base/outline-grid/outline-grid.ts
  src/components/base/outline-grid/test/outline-grid.test.ts
  src/components/base/outline-tabs/outline-tab-group/outline-tab-group.ts
Labels: Ready for Review, BREAKING CHANGE
