Repository phase2/outline, pull requests merged in 2021-08, with the labels that each got.

#88 fix: fixes for usages of outline-header
  src/.storybook/stories/documentation/tooling.stories.mdx
  src/components/base/outline-card/outline-card.stories.ts
  src/components/base/outline-container/outline-container.stories.ts
  src/components/base/outline-grid/outline-column/outline-column.stories.ts
  src/components/base/outline-grid/outline-grid.stories.ts
  src/components/base/outline-heading/outline-heading.stories.ts
  src/imports.d.ts
Labels: Difficulty: Low, Severity: Medium, Type: Bug

#89 feat: upgrade Storybook to 6.3.6
  package.json
  yarn.lock
Labels: Why: Update dependencies

#46 Accordion component
  src/components/base/outline-accordion/outline-accordion.css
  src/components/base/outline-accordion/outline-accordion.stories.ts
  src/components/base/outline-accordion/outline-accordion.ts
Labels: For Review

#99 Adding controllers
  src/components/controllers/mobile-controller.ts
  src/components/controllers/slotted-controller.ts
Labels: Type: Enhancement

#100 fix: delete .npmrc to fix GitLab pipeline issues temporarily
  .npmrc
Labels: Type: Bug

#98 Chromatic for Pull Requests
  .github/workflows/chromatic.yml
  package.json
  yarn.lock
Labels: Why: Reduce adoption friction, Type: Enhancement, Severity: Medium, Ready for Review

#66 Update button component
  src/components/base/outline-button/outline-button.css
  src/components/base/outline-button/outline-button.stories.ts
  src/components/base/outline-button/outline-button.ts
  src/components/base/outline-link/config.ts
Labels: Discussion, Type: Enhancement, Component Suggestion

#75 Docs: Basic html consumer.
  dev/README.md
  dev/index.html
  rollup.config.js
  web-dev-server.config.js
  web-dev-server.config.mjs
Labels: Ready for Review
