Repository phase2/outline, pull requests merged in 2021-09, with the labels that each got.

#96 Feature/breadcrumbs
  outline.theme.css
  src/components/base/outline-breadcrumbs/outline-breadcrumbs.css
  src/components/base/outline-breadcrumbs/outline-breadcrumbs.stories.mdx
  src/components/base/outline-breadcrumbs/outline-breadcrumbs.ts
  src/components/base/outline-breadcrumbs/test/outside-breadcrumbs.test.ts
  tailwind.config.js
Labels: Ready for Review

#114 Lit 2.0.0 stable upgrade
  src/components/base/outline-button/outline-button.stories.ts
  src/components/base/outline-container/outline-container.stories.ts
  src/components/base/outline-grid/outline-column/outline-column.stories.ts
  src/components/base/outline-grid/outline-grid.stories.ts
  src/components/base/outline-heading/outline-heading.stories.ts
  src/components/base/outline-icon/outline-icon.stories.ts
  src/components/base/outline-image/outline-image.stories.ts
  src/components/base/outline-link/outline-link.stories.ts
  src/components/base/outline-modal/outline-modal.stories.ts
  yarn.lock
Labels: Severity: High, Internal Backport

#115 Updating to lit 2.0
  package.json
  yarn.lock
Labels: Internal Backport
