Repository phase2/outline, pull requests merged in 2021-07, with the labels that each got.

#36 Updating Documentation
  CONTRIBUTING.md
  src/.storybook/stories/documentation/contributing.stories.mdx
  src/.storybook/stories/documentation/tooling.stories.mdx
Labels: Documentation

#47 Basic Proton Documentation
  src/.storybook/stories/protons/colors.stories.mdx
  src/.storybook/stories/protons/spacing.stories.mdx
  src/.storybook/stories/protons/typefaces.stories.mdx
Labels: Documentation

#48 Updated documentation
  src/.storybook/main.js
  src/.storybook/stories/documentation/welcome.stories.mdx
  src/.storybook/stories/protons/colors.stories.mdx
  src/.storybook/stories/protons/spacing.stories.mdx
Labels: Documentation

#40 Adding Gitpod ready-to-code
  .gitignore
  .gitpod.Dockerfile
  .gitpod.yml
  .npmrc
  CONTRIBUTING.md
  README.md
  package.json
Labels: Severity: Low, Type: Enhancement, Why: Reduce adoption friction

#63 add testing and refactor stories to work with it
  package.json
  src/components/base/outline-card/outline-card.stories.ts
  src/components/base/outline-container/outline-container.stories.ts
  src/components/base/outline-grid/outline-column/outline-column.stories.ts
  src/components/base/outline-grid/outline-grid.stories.ts
  src/components/base/outline-link/outline-link.stories.ts
  src/components/examples/class-extension/class-extension.stories.ts
  tsconfig.json
  yarn.lock
Labels: DRAFT, Severity: High, Type: Bug

#80 Rollup configuration updates
  rollup.config.js
Labels: Severity: High, Type: Bug

#49 Feature: #45 Modal.
  src/components/base/outline-modal/outline-modal.css
  src/components/base/outline-modal/outline-modal.stories.ts
  src/components/base/outline-modal/outline-modal.ts
  src/components/base/outline-modal/test/outline-modal.test.ts
Labels: Ready for Review
