Repository phase2/outline, pull requests merged in 2022-05, with the labels that each got.

#306 feat(storybook): Upgrade to 6.4.22.
  package.json
  yarn.lock
Labels: Why: Update dependencies

#261 Outline Dropdown & Button Updates
  outline.theme.css
  src/components/base/outline-button/outline-button.css
  src/components/base/outline-button/outline-button.stories.ts
  src/components/base/outline-dropdown/outline-dropdown.css
  src/components/base/outline-dropdown/outline-dropdown.stories.ts
  src/components/base/outline-dropdown/outline-dropdown.ts
  src/components/base/outline-element/outline-element.a11y.css
  src/components/base/outline-element/utils/types.ts
  src/components/base/outline-icon/outline-icon.ts
  src/components/base/outline-split-button/outline-split-button.css
  src/components/base/outline-split-button/outline-split-button.ts
Labels: Difficulty: High, Needs Work, Internal Backport, Type: Feature Request

#269 `outline-button-group` Component
  outline.theme.css
  src/components/base/outline-button-group/outline-button-group.stories.ts
  src/components/base/outline-button-group/outline-button-group.ts
  src/components/base/outline-button-group/test/outline-button-group.test.ts
  src/components/base/outline-list/css-variables/vars-list.css
  src/components/base/outline-list/outline-list.css
  src/components/base/outline-list/outline-list.stories.ts
  src/components/base/outline-list/outline-list.ts
Labels: Needs: Discussion, Needs Work, Held for Review

#318 `outline-image`: Updates to base image component
  outline.config.js
  src/components/base/outline-image/outline-image.css
  src/components/base/outline-image/outline-image.stories.ts
  src/components/base/outline-image/outline-image.ts
  src/components/base/outline-image/test/outline-image.test.ts
  src/data.ts
Labels: Severity: Medium, Ready for Review, Type: Feature Request

#322 feat(a11y): Update to run axe-storybook-testing on prod build.
  .github/workflows/build.yml
  src/components/base/outline-video-vimeo/outline-video-vimeo.stories.ts
  src/components/base/outline-video-youtube/outline-video-youtube.stories.ts
Labels: Ready for Review, Why: Improve Accessibility, Type: Accessibility
