Repository phase2/outline, pull requests merged in 2022-04, with the labels that each got.

#271 feat(storybook): Update Storybook to 6.4.20.
  .gitpod.yml
  package.json
  yarn.lock
Labels: Why: Update dependencies

#270 fix(prettier): Ignore outline.theme.css to allow for intentional formatting
  .prettierignore
Labels: Type: Enhancement, Difficulty: Low

#293 fix(documentation): Adjust docs per story structure.
  src/components/base/outline-icon/outline-icon.stories.ts
Labels: Ready for Review

#295 feat(storybook): Upgrade Storybook to 6.4.21.
  package.json
  yarn.lock
Labels: Why: Update dependencies, Ready for Review

#296 feat(docs): Enhance welcome page.
  src/.storybook/stories/guides/tooling/02-helpful-commands.stories.mdx
  src/.storybook/stories/guides/welcome.stories.mdx
  src/.storybook/stories/protons/spacing.stories.mdx
  src/components/utility/sb-section-link/sb-section-link.css
Labels: Why: Reduce adoption friction, Ready for Review

#237 #236: Adding in mobile controller and CSS config changes to Outline Heading
  outline.theme.css
  src/components/base/outline-heading/config.ts
  src/components/base/outline-heading/outline-heading.css
  src/components/base/outline-heading/outline-heading.stories.ts
  src/components/base/outline-heading/outline-heading.ts
  src/components/base/outline-heading/test/outline-heading.test.ts
  tailwind.config.js
Labels: Feature Request, READY TO CODE

#299 Accordion cleanup.
  src/components/base/outline-accordion-panel/outline-accordion-panel.css
  src/components/base/outline-accordion-panel/outline-accordion-panel.stories.ts
  src/components/base/outline-accordion-panel/outline-accordion-panel.ts
  src/components/base/outline-accordion/outline-accordion.css
  src/components/base/outline-accordion/outline-accordion.stories.ts
  src/components/base/outline-accordion/outline-accordion.ts
  src/components/base/outline-heading/outline-heading.ts
Labels: Coding Standards, BREAKING CHANGE, Why: Increase standardization, READY TO CODE

#305 Let the `MobileController` class be configured per instance
  outline.config.js
  src/components/controllers/mobile-controller.ts
Labels: Ready for Review

#310 Fix for `LinkedBlockController` double click handling
  CONTRIBUTING.md
  src/components/controllers/linked-block-controller.ts
Labels: Type: Bug
